export const BUSINESS = {
  name: 'RoopShree Beauty Parlour',
  tagline: 'Only for Ladies',
  owner: 'Mrs. Barkha Malviya',
  address: '591 Khatupati Complex, Basant Vihar Rd, Opposite Mahima Fancy Store, Kota, Rajasthan 324009',
  phone: '+91-7014234380',
  whatsapp: '917014234380',
  email: 'roopshreebeauty@gmail.com',
  mapsUrl: 'https://maps.app.goo.gl/bU6MYV69TnWGrKRE7',
  hours: {
    weekdays: '9:00 AM – 8:00 PM',
    sunday: '10:00 AM – 6:00 PM',
  },
  rating: 4.8,
  totalReviews: 127,
  totalClients: '2500+',
  yearsExp: '8+',
};

export const SERVICES = [
  {
    id: 1,
    category: 'Hair',
    icon: '✂️',
    color: 'from-pink-100 to-rose-100',
    items: [
      { name: 'Haircut & Styling', price: 200, duration: 45, popular: true },
      { name: 'Hair Color (Global)', price: 1200, duration: 120 },
      { name: 'Hair Highlights', price: 1800, duration: 150 },
      { name: 'Hair Spa', price: 800, duration: 60, popular: true },
      { name: 'Keratin Treatment', price: 3500, duration: 180 },
      { name: 'Smoothening', price: 4000, duration: 240 },
      { name: 'Rebonding', price: 3000, duration: 240 },
      { name: 'Hair Botox', price: 2500, duration: 120 },
    ],
  },
  {
    id: 2,
    category: 'Skin',
    icon: '✨',
    color: 'from-purple-100 to-pink-100',
    items: [
      { name: 'Gold Facial', price: 1200, duration: 60, popular: true },
      { name: 'Diamond Facial', price: 1500, duration: 75 },
      { name: 'Cleanup', price: 500, duration: 45 },
      { name: 'Detan Facial', price: 800, duration: 60 },
      { name: 'Anti-Aging Facial', price: 1800, duration: 90 },
      { name: 'Bleach (Full Face)', price: 300, duration: 30 },
      { name: 'Threading (Eyebrows)', price: 50, duration: 10 },
      { name: 'Upper Lip Threading', price: 30, duration: 5 },
    ],
  },
  {
    id: 3,
    category: 'Makeup',
    icon: '💄',
    color: 'from-red-100 to-pink-100',
    items: [
      { name: 'Bridal Makeup (HD)', price: 10000, duration: 180, popular: true },
      { name: 'Party Makeup', price: 2500, duration: 90 },
      { name: 'Engagement Makeup', price: 5000, duration: 120 },
      { name: 'Pre-Bridal Package', price: 8000, duration: 240 },
      { name: 'Mehndi Makeup', price: 3000, duration: 90 },
      { name: 'Reception Makeup', price: 6000, duration: 150 },
    ],
  },
  {
    id: 4,
    category: 'Nails',
    icon: '💅',
    color: 'from-yellow-100 to-orange-100',
    items: [
      { name: 'Manicure (Basic)', price: 350, duration: 40 },
      { name: 'Pedicure (Basic)', price: 450, duration: 50 },
      { name: 'Gel Nail Polish', price: 600, duration: 45, popular: true },
      { name: 'Nail Art', price: 800, duration: 60 },
      { name: 'French Manicure', price: 700, duration: 50 },
      { name: 'Manicure + Pedicure Combo', price: 700, duration: 90 },
    ],
  },
  {
    id: 5,
    category: 'Waxing',
    icon: '🌿',
    color: 'from-green-100 to-teal-100',
    items: [
      { name: 'Full Arms Wax', price: 200, duration: 30 },
      { name: 'Full Legs Wax', price: 350, duration: 45 },
      { name: 'Full Body Wax', price: 1200, duration: 120, popular: true },
      { name: 'Underarms Wax', price: 100, duration: 15 },
      { name: 'Rica Wax (Full Legs)', price: 600, duration: 50 },
      { name: 'Rica Wax (Full Body)', price: 1800, duration: 120 },
    ],
  },
  {
    id: 6,
    category: 'Packages',
    icon: '👑',
    color: 'from-amber-100 to-yellow-100',
    items: [
      { name: 'Bridal Package (Full)', price: 25000, duration: 480, popular: true },
      { name: 'Pre-Bridal (5 Sessions)', price: 8000, duration: 300 },
      { name: 'Monthly Glow Package', price: 2500, duration: 180 },
      { name: 'Student Special', price: 999, duration: 120, popular: true },
    ],
  },
];

export const FEATURED_SERVICES = [
  { name: 'Bridal Makeup', price: '₹10,000', icon: '👰', desc: 'HD/Airbrush Bridal Makeup with trial session', tag: 'Most Popular' },
  { name: 'Gold Facial', price: '₹1,200', icon: '✨', desc: 'Deep cleansing Gold Facial for glowing skin', tag: 'Best Seller' },
  { name: 'Hair Spa', price: '₹800', icon: '💆‍♀️', desc: 'Nourishing hair spa for silky smooth hair', tag: 'Recommended' },
  { name: 'Full Body Wax', price: '₹1,200', icon: '🌿', desc: 'Rica/Chocolate wax for smooth & soft skin', tag: 'Value Deal' },
];

export const OFFERS = [
  {
    id: 1,
    title: 'Bridal Bonanza',
    discount: '20% OFF',
    description: 'Complete Bridal Package including Makeup, Hair & Pre-bridal facials',
    originalPrice: '₹30,000',
    offerPrice: '₹24,000',
    validity: 'Valid till 30 June 2026',
    badge: '🔥 Hot Deal',
    code: 'BRIDE20',
  },
  {
    id: 2,
    title: 'Summer Glow Package',
    discount: 'FLAT ₹500 OFF',
    description: 'Detan Facial + Cleanup + Pedicure + Full Arms Wax',
    originalPrice: '₹1,600',
    offerPrice: '₹1,100',
    validity: 'Limited Time Offer',
    badge: '☀️ Summer Special',
    code: 'GLOW500',
  },
  {
    id: 3,
    title: 'Student Special',
    discount: '30% OFF',
    description: 'Haircut + Cleanup + Threading on showing valid student ID',
    originalPrice: '₹800',
    offerPrice: '₹560',
    validity: 'Every Monday–Wednesday',
    badge: '🎓 Students Only',
    code: 'STUDENT30',
  },
];

export const REVIEWS = [
  {
    id: 1,
    name: 'Priya Sharma',
    initials: 'PS',
    rating: 5,
    date: '2 weeks ago',
    review: 'Best parlour in Kota! Got my bridal makeup done here and I looked absolutely stunning on my wedding day. The team is so professional and patient. They did a trial session first which was really helpful. Highly recommend to all brides-to-be!',
    service: 'Bridal Makeup',
    color: 'bg-pink-500',
  },
  {
    id: 2,
    name: 'Anita Gupta',
    initials: 'AG',
    rating: 5,
    date: '1 month ago',
    review: 'Very hygienic place with highly skilled staff. The hair color and cutting service is excellent. I got balayage done and the results were beyond my expectations. Prices are very reasonable compared to other parlours in Kota.',
    service: 'Hair Color & Cut',
    color: 'bg-purple-500',
  },
  {
    id: 3,
    name: 'Meena Verma',
    initials: 'MV',
    rating: 5,
    date: '3 weeks ago',
    review: "I've been visiting RoopShree for over 2 years now. The facial and cleanup they do is absolutely amazing. My skin feels fresh and glowing after every session. The staff remembers my preferences which shows how much they care about regular customers!",
    service: 'Gold Facial',
    color: 'bg-rose-500',
  },
  {
    id: 4,
    name: 'Sunita Jain',
    initials: 'SJ',
    rating: 4,
    date: '5 days ago',
    review: 'Good service and very friendly staff. Got pedicure and manicure done for my daughter\'s engagement ceremony. They did such a beautiful job! The nail art was exactly what we wanted. Location is easy to find near Basant Vihar Road.',
    service: 'Manicure & Pedicure',
    color: 'bg-amber-500',
  },
  {
    id: 5,
    name: 'Kavya Rajput',
    initials: 'KR',
    rating: 5,
    date: '2 months ago',
    review: 'Outstanding work! The mehendi makeup and hair styling for my sister\'s wedding was done so beautifully. Everyone at the wedding was asking who did the makeup. The prices are affordable and the quality is absolutely top-notch. Will definitely be back!',
    service: 'Wedding Makeup',
    color: 'bg-emerald-500',
  },
  {
    id: 6,
    name: 'Rekha Patel',
    initials: 'RP',
    rating: 5,
    date: '1 week ago',
    review: 'Clean, professional and very affordable salon. I got the keratin hair treatment done and my hair has never felt this smooth and manageable. The staff is very knowledgeable about hair care and gave me great tips for maintaining the treatment at home.',
    service: 'Keratin Treatment',
    color: 'bg-teal-500',
  },
];

// Real photos of RoopShree Beauty Parlour, Kota (stored in /public/gallery)
export const GALLERY_IMAGES = [
  // --- Makeup ---
  { src: '/gallery/parlour-3.jpg', alt: 'Bridal Makeup (Red Lehenga)', category: 'Makeup' },
  { src: '/gallery/parlour-13.jpg', alt: 'Bridal Makeup', category: 'Makeup' },
  { src: '/gallery/parlour-1.jpg', alt: 'Bridal Eye Makeup', category: 'Makeup' },
  { src: '/gallery/parlour-18.jpg', alt: 'Bridal Makeup', category: 'Makeup' },
  { src: '/gallery/parlour-7.jpg', alt: 'Bridal Look', category: 'Makeup' },
  { src: '/gallery/parlour-14.jpg', alt: 'Engagement Look', category: 'Makeup' },
  { src: '/gallery/parlour-15.jpg', alt: 'Engagement Look', category: 'Makeup' },
  { src: '/gallery/parlour-2.jpg', alt: 'Engagement Look', category: 'Makeup' },
  { src: '/gallery/parlour-5.jpg', alt: 'Party Makeup & Hair Styling', category: 'Makeup' },
  { src: '/gallery/parlour-9.jpg', alt: 'Glamour Makeup', category: 'Makeup' },
  { src: '/gallery/parlour-11.jpg', alt: 'Bridal Makeup & Jewellery', category: 'Makeup' },
  { src: '/gallery/parlour-17.jpg', alt: 'Glamour Makeup', category: 'Makeup' },
  { src: '/gallery/parlour-19.jpg', alt: 'Party Makeup', category: 'Makeup' },
  // --- Hair ---
  { src: '/gallery/parlour-12.jpg', alt: 'Bridal Hair Styling', category: 'Hair' },
  { src: '/gallery/parlour-10.jpg', alt: 'Haircut — Before & After', category: 'Hair' },
  // --- Skin ---
  { src: '/gallery/parlour-8.jpg', alt: 'Acne Treatment — Before & After', category: 'Skin' },
  // --- Salon ---
  { src: '/gallery/parlour-16.jpg', alt: 'Bridal Makeup Session', category: 'Salon' },
  { src: '/gallery/parlour-6.jpg', alt: 'Happy Bride with Our Artist', category: 'Salon' },
  { src: '/gallery/parlour-4.jpg', alt: 'Our Parlour', category: 'Salon' },
];

export const TIME_SLOTS = [
  '9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM',
  '11:00 AM', '11:30 AM', '12:00 PM', '12:30 PM',
  '2:00 PM', '2:30 PM', '3:00 PM', '3:30 PM',
  '4:00 PM', '4:30 PM', '5:00 PM', '5:30 PM',
  '6:00 PM', '6:30 PM', '7:00 PM',
];

export const QUICK_SERVICES = [
  { label: 'Hair', icon: '✂️', desc: 'Cut, Color & Spa', href: '/services#hair' },
  { label: 'Skin', icon: '✨', desc: 'Facials & Cleanup', href: '/services#skin' },
  { label: 'Makeup', icon: '💄', desc: 'Bridal & Party', href: '/services#makeup' },
  { label: 'Nails', icon: '💅', desc: 'Manicure & Art', href: '/services#nails' },
];
